Canvas no types
KTH/azure-functions-sandbox pull request #2
Opened 2022-03-22 15:23 UTC by jhsware

This is the version with strong typing removed.

2022-03-23 07:40 UTC, exacs requested changes
I know that there are lots of comments in this review (maybe even more than code) but most of the comments are minor details:

There is no problem with how you write code but rather how to interact with Canvas (using sections, the correct SIS ID format) and some gotchas regarding programming for Azure Functions.

2022-03-23 07:40 UTC, exacs commented on RemoveUnregisteredStudent/canvasApi.ts
> +    `courses/sis_course_id:${activityRoundId}/enrollments`,
- SIS ID for examination rooms is not exactly «activity round id» but `AKT.«activity round id»`. Example: https://kth.test.instructure.com/api/v1/courses/34520
- It could happen that an examination room is empty because the section has been moved somewhere else. We use sections to ensure students are located in the right place. So fetch the enrollments using sections.
- I think it is better to add the URL for the canvas api documentation, not the ruby controller in the source code.
- You don't need to pass `type[]` parameter. Instead use `type: ["StudentEnrollment"]`. `canvas-api` will convert the array to the correct format
- [According to the docs](https://canvas.instructure.com/doc/api/enrollments.html#method.enrollments_api.index) the endpoint return a **list** of enrollments, not **one**. The type parameter `<{ id: number }>` is not correct here and in the function header

2022-03-23 07:40 UTC, exacs commented on RemoveUnregisteredStudent/canvasApi.ts
> +    `courses/sis_course_id:${activityRoundId}/enrollments/${enrollmentId}?task=delete`,
Same here:

- Replace courses with sections
- Use the correct SIS ID (missing prefix "AKT.")
- Replace the URL (the comment) with the URL to the docs instead of source code

2022-03-23 07:40 UTC, exacs commented on RemoveUnregisteredStudent/index.ts
> +import { assert } from "console";
Are you sure you want to use `console.assert`? https://nodejs.org/api/console.html#consoleassertvalue-message

And not `import assert from "assert"`?

2022-03-23 07:40 UTC, exacs commented on RemoveUnregisteredStudent/index.ts
> +    assert(studentId, "Message is missing 'studentId'");
`assert` here means that the message will be marked as "undeliverable". Since we are not filtering messages, every message not containing those fields will be marked as error.

I think it is better to **ignore** the messages (exit the function without error)

2022-03-23 07:40 UTC, exacs commented on RemoveUnregisteredStudent/ug.ts
> +export async function getKthId(ladokUid: string) : Promise<string> {
🎉

2022-03-23 07:40 UTC, exacs commented on RemoveUnregisteredStudent/canvasApi.ts
> +import { assert } from "console";
Are you sure you want to use `console.assert`? https://nodejs.org/api/console.html#consoleassertvalue-message

And not `import assert from "assert"`?

2022-03-23 07:42 UTC, exacs commented on RemoveUnregisteredStudent/canvasApi.ts
> +}
If the problem is "missing environmental variable", I think it is better to crash the app as soon as possible, without even trying to receive a message. With this implementation, the app is able to receive messages but all will be marked as "errored"

(I prefer that the app crashes here instead of within `getCourseEnrollment` function)

2022-03-23 07:48 UTC, jhsware commented on RemoveUnregisteredStudent/canvasApi.ts
> +    `courses/sis_course_id:${activityRoundId}/enrollments`,
Will fix!

2022-03-23 07:49 UTC, jhsware commented on RemoveUnregisteredStudent/canvasApi.ts
> +
@exacs Should we fix this in this project? Considering it is only a sandbox app perhaps we should implement the error handling properly in the real project.

2022-03-23 07:49 UTC, jhsware commented on RemoveUnregisteredStudent/canvasApi.ts
> +    `courses/sis_course_id:${activityRoundId}/enrollments/${enrollmentId}?task=delete`,
Will fix!

2022-03-23 07:50 UTC, jhsware commented on RemoveUnregisteredStudent/index.ts
> +import { assert } from "console";
Will fix!

Good point! That was an auto-import by VS Code. I shouldn't have let it linger!

2022-03-23 07:51 UTC, jhsware commented on RemoveUnregisteredStudent/index.ts
> +    assert(studentId, "Message is missing 'studentId'");
Will fix!

2022-03-23 07:52 UTC, jhsware commented on RemoveUnregisteredStudent/canvasApi.ts
> +import { assert } from "console";
Will fix!

2022-03-23 07:53 UTC, jhsware commented on RemoveUnregisteredStudent/canvasApi.ts
> +}
Will fix! This code was related to testing woes we had in our CI-pipeling.

2022-03-23 07:57 UTC, jhsware commented on RemoveUnregisteredStudent/canvasApi.ts
> +
We decided to let this go.

2022-03-24 10:32 UTC, jhsware commented on RemoveUnregisteredStudent/index.ts
> +import { assert } from "console";
Fixed in 20f8000

2022-03-24 10:34 UTC, jhsware commented on RemoveUnregisteredStudent/canvasApi.ts
> +}
Fixed in bdb0340

2022-03-24 13:50 UTC, jhsware commented on RemoveUnregisteredStudent/canvasApi.ts
> +    `courses/sis_course_id:${activityRoundId}/enrollments`,
Fixed in 7d2cc32

2022-03-24 13:51 UTC, jhsware commented on RemoveUnregisteredStudent/canvasApi.ts
> +    `courses/sis_course_id:${activityRoundId}/enrollments/${enrollmentId}?task=delete`,
Fixed in 7d2cc32

2022-03-25 07:17 UTC, exacs approved these changes

2022-03-25 07:18 UTC, merged